#!/usr/bin/env python3
"""Real localhost server used by Swift integration tests."""
import http.server
import os
import signal
import socket
import socketserver
import sys

mode = os.environ.get("FAKE_DSH_MODE", "token")
marker = os.environ.get("FAKE_DSH_MARKER")
if mode == "exit":
    print("fixture exited before listening", flush=True)
    sys.exit(7)
if mode == "exit-secret":
    print("failure token=do-not-log-this", flush=True)
    sys.exit(7)


class Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        authorized = mode != "token" or "token=test-secret" in self.path
        self.send_response(200 if authorized else 401)
        self.end_headers()
        self.wfile.write(b"dsh fixture" if authorized else b"token required")

    def log_message(self, *args):
        pass


class FastHTTPServer(http.server.HTTPServer):
    def server_bind(self):
        # HTTPServer normally calls getfqdn(host), which can block for tens of
        # seconds on CI and has no purpose for this loopback fixture.
        socketserver.TCPServer.server_bind(self)
        self.server_name = self.server_address[0]
        self.server_port = self.server_address[1]


host = os.environ.get("FAKE_DSH_HOST", "127.0.0.1")
if host == "::1":
    class IPv6Server(FastHTTPServer):
        address_family = socket.AF_INET6
    server = IPv6Server((host, 0), Handler)
else:
    server = FastHTTPServer((host, 0), Handler)
url_host = "[::1]" if host == "::1" else host
url = f"http://{url_host}:{server.server_address[1]}/"
if mode == "token":
    url += "?token=test-secret"
if mode != "silent":
    print(f"dsh web: {url}", flush=True)
if mode == "exit-later":
    signal.signal(signal.SIGALRM, lambda *_: sys.exit(0))
    signal.alarm(3)


def stop(*args):
    if marker:
        with open(marker, "w", encoding="utf-8") as output:
            output.write("terminated")
    sys.exit(0)


signal.signal(signal.SIGTERM, stop)
server.serve_forever()
