#!/usr/bin/env python3
"""Real localhost server used by Swift integration tests."""
import http.server
import os
import signal
import socket
import sys

mode = os.environ.get("FAKE_DSH_MODE", "token")
marker = os.environ.get("FAKE_DSH_MARKER")
if mode == "exit":
    print("fixture exited before listening", flush=True)
    sys.exit(7)
if mode == "exit-secret":
    print("failure token=do-not-log-this", flush=True)
    sys.exit(7)


class Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        authorized = mode != "token" or "token=test-secret" in self.path
        self.send_response(200 if authorized else 401)
        self.end_headers()
        self.wfile.write(b"dsh fixture" if authorized else b"token required")

    def log_message(self, *args):
        pass


host = os.environ.get("FAKE_DSH_HOST", "127.0.0.1")
if host == "::1":
    class IPv6Server(http.server.HTTPServer):
        address_family = socket.AF_INET6
    server = IPv6Server((host, 0), Handler)
else:
    server = http.server.HTTPServer((host, 0), Handler)
port_file = os.environ.get("FAKE_DSH_PORT_FILE")
if port_file:
    with open(port_file, "w", encoding="utf-8") as output:
        output.write(str(server.server_address[1]))
url_host = "[::1]" if host == "::1" else host
url = f"http://{url_host}:{server.server_address[1]}/"
if mode == "token":
    url += "?token=test-secret"
if mode != "silent":
    print(f"dsh web: {url}", flush=True)
if mode == "exit-later":
    signal.signal(signal.SIGALRM, lambda *_: sys.exit(0))
    signal.alarm(1)


def stop(*args):
    if marker:
        with open(marker, "w", encoding="utf-8") as output:
            output.write("terminated")
    sys.exit(0)


signal.signal(signal.SIGTERM, stop)
server.serve_forever()
